"""Hard-rule evaluation report helpers.

The main report is now cases_report.html generated by generate_case_html.py.
This module retains the _render_* helper functions used by tests.
"""
from __future__ import annotations

import json
import sys
from collections import Counter
from pathlib import Path
from datetime import datetime

sys.path.insert(0, str(Path(__file__).parent))
from evaluator import (
    CHECKLIST,
    evaluate_generated_cases,
)
from manual_review import (
    load_review_scores,
)


def _generate_report(round_dir: Path, round_num: int, max_rounds: int = 5, prev_rate: float | None = None) -> float:
    cases_path = round_dir / "generated_cases.json"
    with open(cases_path, encoding="utf-8") as f:
        data = json.load(f)

    review_entries = None
    review_path = round_dir / "manual_review_scores.json"
    if review_path.exists():
        try:
            review_entries = load_review_scores(str(review_path))
        except ValueError as exc:
            review_entries = None
            review_error = str(exc)
        else:
            review_error = ""
    else:
        review_error = ""

    evaluation = evaluate_generated_cases(data, review_entries)
    total_cases = evaluation.total_cases
    total_passed = evaluation.total_passed
    case_pass_rate = evaluation.case_pass_rate
    case_failures = [
        (f"{case.requirement_key} :: {case.case_title[:60]}", case.failed_items)
        for case in evaluation.case_results.values()
        if case.failed_items
    ]
    item_fail_counts = evaluation.item_fail_counts
    item_warning_counts = evaluation.item_warning_counts
    hard_gate_records = evaluation.hard_gate_records
    review_summary = evaluation.manual_review_summary
    if review_error:
        review_summary = {"_error": review_error}

    req_count = len(data)

    # Per-item pass rates
    item_data = []
    cat_rates = {
        "1. 结构完整性": [],
        "2. 领域正确性": [],
        "3. NEEDS REVIEW规范": [],
        "4. 步骤质量": [],
        "5. 覆盖维度": [],
        "6. 测试工程深度": [],
    }
    for item_id, (desc, cat) in CHECKLIST.items():
        fail_count = item_fail_counts.get(item_id, 0)
        item_pass_rate = round((1 - fail_count / total_cases) * 100, 1) if total_cases else 100
        status = "pass" if item_pass_rate >= 90 else "fail"
        item_data.append((item_id, desc, cat, item_pass_rate, status, fail_count))
        if cat in cat_rates:
            cat_rates[cat].append(item_pass_rate)

    cat_avg = {}
    for cat, rates in cat_rates.items():
        cat_avg[cat] = round(sum(rates) / len(rates), 1) if rates else 100

    # Build HTML
    overall_color = "#22c55e" if case_pass_rate >= 90 else "#f59e0b" if case_pass_rate >= 70 else "#ef4444"
    improvement_str = "—"
    if prev_rate is not None:
        delta = round(case_pass_rate - prev_rate, 1)
        sign = "+" if delta > 0 else ""
        improvement_str = f"{sign}{delta}%"

    # Category rows
    cat_rows = []
    for name, rate in cat_avg.items():
        color = "#22c55e" if rate >= 90 else "#f59e0b" if rate >= 75 else "#ef4444"
        fill = "pass" if rate >= 90 else "fail"
        cat_rows.append(
            f'<tr><td>{name}</td>'
            f'<td style="color:{color};font-weight:700">{rate}%</td>'
            f'<td>90%</td>'
            f'<td><div class="progress-bar" style="width:120px"><div class="progress-fill {fill}" style="width:{rate}%"></div></div></td></tr>'
        )

    # Item rows
    item_rows = []
    for item_id, desc, cat, rate, status, fail_count in item_data:
        badge = "pass" if status == "pass" else "fail"
        stext = "PASS" if status == "pass" else "FAIL"
        color = "var(--pass)" if status == "pass" else "var(--fail)"
        item_rows.append(
            f'<tr><td>{item_id}</td><td>{desc}</td><td>{cat}</td>'
            f'<td style="font-weight:700;color:{color}">{rate}%</td>'
            f'<td><span class="badge {badge}">{stext}</span></td>'
            f'<td>{fail_count} cases failed</td></tr>'
        )

    # Top failures
    top_fail_items = sorted(item_data, key=lambda x: x[4])[:12]  # lowest pass rate
    top_rows = []
    for item_id, desc, cat, rate, status, fail_count in top_fail_items:
        if fail_count == 0:
            continue
        top_rows.append(
            f'<tr><td>{item_id}</td><td>{desc}</td>'
            f'<td style="color:var(--fail);font-weight:700">{rate}%</td>'
            f'<td>{fail_count}/{total_cases} cases</td></tr>'
        )
    top_fail_html = "\n".join(top_rows[:10])

    # Failed case samples
    failed_case_html = ""
    for case_key, failed_items in case_failures[:8]:
        items_str = ", ".join(failed_items)
        failed_case_html += f'<tr><td>{case_key}</td><td style="color:var(--fail)">{len(failed_items)}</td><td style="font-size:0.82rem">{items_str}</td></tr>'

    status_text = "达标" if case_pass_rate >= 90 else "未达标"

    html = f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>评估报告 — Round {round_num} / {max_rounds} — Testcase Agent</title>
<style>
  :root {{
    --pass: #22c55e; --fail: #ef4444; --warn: #f59e0b;
    --bg: #f8fafc; --card: #ffffff; --border: #e2e8f0;
    --text: #1e293b; --muted: #64748b;
  }}
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: var(--bg); color: var(--text); line-height: 1.6; padding: 24px; }}
  .container {{ max-width: 1200px; margin: 0 auto; }}
  h1 {{ font-size: 1.75rem; margin-bottom: 4px; }}
  h2 {{ font-size: 1.25rem; margin: 24px 0 12px; padding-bottom: 6px; border-bottom: 2px solid var(--border); }}
  .subtitle {{ color: var(--muted); font-size: 0.9rem; margin-bottom: 24px; }}
  .summary-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 12px; margin-bottom: 24px; }}
  .summary-card {{ background: var(--card); border: 1px solid var(--border); border-radius: 8px; padding: 16px; text-align: center; }}
  .summary-card .value {{ font-size: 2rem; font-weight: 700; }}
  .summary-card .label {{ color: var(--muted); font-size: 0.85rem; margin-top: 4px; }}
  .progress-bar {{ height: 24px; background: #e2e8f0; border-radius: 12px; overflow: hidden; margin: 8px 0; }}
  .progress-fill {{ height: 100%; border-radius: 12px; }}
  .progress-fill.pass {{ background: var(--pass); }}
  .progress-fill.fail {{ background: var(--fail); }}
  table {{ width: 100%; border-collapse: collapse; background: var(--card); border: 1px solid var(--border); border-radius: 8px; overflow: hidden; margin-bottom: 16px; font-size: 0.88rem; }}
  th, td {{ padding: 10px 14px; text-align: left; }}
  th {{ background: #f1f5f9; font-weight: 600; border-bottom: 2px solid var(--border); }}
  td {{ border-bottom: 1px solid var(--border); }}
  tr:last-child td {{ border-bottom: none; }}
  .badge {{ display: inline-block; padding: 2px 10px; border-radius: 12px; font-size: 0.78rem; font-weight: 600; }}
  .badge.pass {{ background: #dcfce7; color: #166534; }}
  .badge.fail {{ background: #fecaca; color: #991b1b; }}
  .note {{ background: #fefce8; border-left: 4px solid var(--warn); border-radius: 4px; padding: 12px 16px; margin: 16px 0; font-size: 0.9rem; }}
</style>
</head>
<body>
<div class="container">

<h1>BMS HIL 测试用例质量评估报告</h1>
<p class="subtitle">
  Round <strong>{round_num} / {max_rounds}</strong>
  | Cases: <strong>{total_cases}</strong>
  | Reqs: <strong>{req_count}</strong>
  | Time: <strong>{datetime.now().strftime("%Y-%m-%d %H:%M")}</strong>
</p>

<div class="note">
  <strong>评估方式:</strong> Case 级通过率 = CHECKLIST 项全部 PASS 的 case 数 / 总 case 数。
  一个 case 只要有一项不通过即算 FAIL。WARNING 项不计入通过率。
</div>

<div class="summary-grid">
  <div class="summary-card">
    <div class="value" style="color:{overall_color}">{case_pass_rate}%</div>
    <div class="label">Case 级通过率 (目标 ≥90%)</div>
  </div>
  <div class="summary-card">
    <div class="value">{total_passed} / {total_cases}</div>
    <div class="label">全 PASS case / 总 case</div>
  </div>
  <div class="summary-card">
    <div class="value">{len(case_failures)}</div>
    <div class="label">有缺陷的 case</div>
  </div>
  <div class="summary-card">
    <div class="value">{improvement_str}</div>
    <div class="label">较上轮变化</div>
  </div>
</div>

<div class="progress-bar">
  <div class="progress-fill {"pass" if case_pass_rate>=90 else "fail"}" style="width:{max(case_pass_rate, 2)}%"></div>
</div>
<p style="text-align:center;color:var(--muted);font-size:0.85rem;margin-top:4px">
  目标: 90% | {status_text} ({case_pass_rate}% {"≥" if case_pass_rate>=90 else "<"} 90%)
</p>

<h2>检查项通过率（参考）</h2>
<table>
  <tr><th>分类</th><th>Item-Avg 通过率</th><th>目标</th><th></th></tr>
  {"".join(cat_rows)}
</table>

<h2>失败最多的检查项</h2>
<table>
  <tr><th>#</th><th>检查项</th><th>通过率</th><th>影响范围</th></tr>
  {top_fail_html}
</table>

<h2>全部检查项</h2>
<table>
  <tr><th>#</th><th>检查项</th><th>分类</th><th>通过率</th><th>状态</th><th>失败数</th></tr>
  {"".join(item_rows)}
</table>

{_render_warning_items(item_warning_counts, total_cases)}

<h2>失败 case 样例</h2>
<table>
  <tr><th>Case</th><th>失败项数</th><th>失败项</th></tr>
  {failed_case_html}
</table>

<h2>Missing Information Hard Gates</h2>
<p style="color:var(--muted);font-size:0.88rem;margin-bottom:8px">
  比较 Prompt Evaluation Set 的 expected_missing_categories 与 LLM#1 实际输出的 missing_info_items。
  仅适用于通过 <code>--requirement-set</code> 生成的 run。
</p>
{_render_hard_gate_section(hard_gate_records)}

{_render_manual_review_section(review_summary)}

</div>
</body>
</html>"""

    report_path = round_dir / "evaluation_report.html"
    report_path.write_text(html, encoding="utf-8")
    print(f"Round {round_num}: case_pass_rate={case_pass_rate}% ({total_passed}/{total_cases}) -> {report_path}")
    return case_pass_rate


def _render_hard_gate_section(records: list[dict]) -> str:
    """Render the Missing Information Hard Gates HTML."""
    if not records:
        return "<p style='color:var(--muted)'>无 Prompt Evaluation Set 数据。使用 <code>--requirement-set</code> 生成 run 后可显示缺失信息硬门禁评估。</p>"

    rows: list[str] = []
    for rec in records:
        req_key = rec["requirement_key"]
        bucket = rec["evaluation_bucket"]
        expected = ", ".join(rec["expected_missing_categories"]) or "—"
        actual = ", ".join(rec["actual_missing_categories"]) or "—"
        item_ids = ", ".join(rec.get("item_ids", [])) or "—"

        severity = ""
        issue_color = "var(--muted)"
        if rec["missing_from_actual"]:
            severity = "⚠️ LLM#1 遗漏"
            issue_color = "var(--fail)"
        elif rec["extra_in_actual"]:
            severity = "ℹ️ LLM#1 多报"
            issue_color = "var(--warn)"
        elif rec["case_issues"]:
            severity = "⚠️ case 缺 [NEEDS REVIEW]"
            issue_color = "var(--fail)"
        else:
            severity = "✅ 匹配"
            issue_color = "var(--pass)"

        case_detail = ""
        for ci in rec["case_issues"]:
            item_id = ci.get("item_id", "")
            case_detail += (
                f'<div style="font-size:0.8rem;color:var(--fail);margin-left:16px">'
                f'  [{item_id}] {ci["case_title"][:80]} — {ci["issue"]}'
                f'  ({", ".join(ci["missing_categories"])})'
                f'</div>'
            )

        rows.append(f"""<tr>
          <td>{req_key}</td>
          <td style="font-size:0.82rem">{bucket}</td>
          <td style="font-size:0.85rem">{expected}</td>
          <td style="font-size:0.85rem">{actual}</td>
          <td style="color:{issue_color};font-weight:600">{severity}</td>
          <td style="font-size:0.82rem">{item_ids}</td>
          <td style="font-size:0.82rem">{case_detail if case_detail else '—'}</td>
        </tr>""")

    return f"""<table>
      <tr>
        <th>Requirement</th>
        <th>Bucket</th>
        <th>Expected Missing</th>
        <th>Actual Missing</th>
        <th>Severity</th>
        <th>Item IDs</th>
        <th>Case Issues</th>
      </tr>
      {"".join(rows)}
    </table>"""


def _render_warning_items(warning_counts: Counter, total_cases: int) -> str:
    """Render WARNING-only checklist items that do not count toward pass/fail."""
    if not warning_counts:
        return ""

    rows: list[str] = []
    for item_id in sorted(warning_counts.keys()):
        count = warning_counts[item_id]
        desc, cat = CHECKLIST.get(item_id, (item_id, ""))
        rows.append(
            f"<tr><td>{item_id}</td><td>{desc}</td><td>{cat}</td>"
            f"<td>{count}</td><td style='color:var(--warn);font-weight:600'>WARNING</td></tr>"
        )

    return f"""
    <h2>WARNING 检查项</h2>
    <p style="color:var(--muted);font-size:0.88rem;margin-bottom:8px">
      WARNING 项不计入 case pass/fail。以下展示触发次数供审阅。
    </p>
    <table>
      <tr><th>#</th><th>检查项</th><th>分类</th><th>触发次数</th><th>级别</th></tr>
      {"".join(rows)}
    </table>"""


def _render_manual_review_section(review_summary: dict) -> str:
    """Render the Manual Review Score section if review data is present."""
    if not review_summary:
        return ""

    if "_error" in review_summary:
        return f"""
        <h2>Manual Review Scores</h2>
        <p style="color:var(--fail)">加载 review 文件失败: {review_summary["_error"]}</p>"""

    avg = review_summary["average_weighted_score"]
    dim_avg = review_summary["dimension_averages"]
    total_requirements = review_summary.get("total_requirements", review_summary.get("total_entries", 0))
    total_cases = review_summary.get("total_cases", review_summary.get("total_entries", 0))
    unacceptable_count = review_summary["total_unacceptable"]
    dist = review_summary["score_distribution"]

    # Score color
    if avg >= 4.0:
        score_color = "var(--pass)"
    elif avg >= 3.0:
        score_color = "var(--warn)"
    else:
        score_color = "var(--fail)"

    # Dimension averages
    dim_rows = []
    dim_labels = {
        "requirement_alignment": "Requirement Alignment (20%)",
        "information_integrity": "Information Integrity (20%)",
        "executability": "Executability (15%)",
        "observability": "Observability (15%)",
        "pass_fail_clarity": "Pass/Fail Clarity (10%)",
        "coverage_value": "Coverage Value (10%, requirement-level)",
        "state_and_environment_control": "State & Environment (5%)",
        "automation_readiness": "Automation Readiness (5%)",
    }
    for dim, label in dim_labels.items():
        val = dim_avg.get(dim, 0)
        min_val = review_summary.get("dimension_mins", {}).get(dim, 0)
        color = "var(--pass)" if val >= 4 else "var(--warn)" if val >= 3 else "var(--fail)"
        dim_rows.append(
            f"<tr><td>{label}</td>"
            f"<td style='font-weight:700;color:{color}'>{val}</td>"
            f"<td>{min_val}</td></tr>"
        )

    # Unacceptable list
    unacceptable_html = ""
    if review_summary["unacceptable"]:
        items = ""
        for u in review_summary["unacceptable"]:
            reasons = "; ".join(u["unacceptable_reasons"])
            items += (
                f"<tr><td>{u['requirement_key']}</td>"
                f"<td>{u['case_title']}</td>"
                f"<td style='color:var(--fail);font-size:0.85rem'>{reasons}</td></tr>"
            )
        unacceptable_html = f"""
        <h3 style="margin-top:12px">❌ Unacceptable Cases ({unacceptable_count})</h3>
        <table>
          <tr><th>Requirement</th><th>Case</th><th>Reason</th></tr>
          {items}
        </table>"""

    # Score distribution
    dist_bars = ""
    for bucket, count in dist.items():
        pct = round(count / total_requirements * 100) if total_requirements else 0
        bar_color = "var(--pass)" if bucket in ("4-5", "3-4") else "var(--warn)"
        dist_bars += (
            f'<div style="display:flex;align-items:center;gap:8px;margin:2px 0">'
            f'<span style="width:40px;font-size:0.82rem">{bucket}</span>'
            f'<div class="progress-bar" style="flex:1;max-width:200px;margin:0">'
            f'<div class="progress-fill" style="width:{max(pct, 2)}%;background:{bar_color}"></div>'
            f'</div><span style="font-size:0.82rem;color:var(--muted)">{count} requirement(s)</span></div>'
        )

    # Detail table (top 10 cases by parent requirement weighted score ascending)
    details = review_summary.get("entry_details", [])
    details_sorted = sorted(details, key=lambda d: d.get("requirement_weighted_score", d.get("weighted_score", 0)))[:10]
    detail_rows = ""
    for d in details_sorted:
        status = "❌" if d["unacceptable"] else "✅"
        warn_note = ""
        if d["warnings"]:
            warn_note = ' <span style="color:var(--warn);font-size:0.78rem">[WARN]</span>'
        detail_rows += (
            f"<tr>"
            f"<td>{d['requirement_key']}</td>"
            f"<td style='font-size:0.85rem'>{d['case_title']}</td>"
            f"<td>{d['requirement_alignment']}</td><td>{d['information_integrity']}</td>"
            f"<td>{d['executability']}</td><td>{d['observability']}</td>"
            f"<td>{d['pass_fail_clarity']}</td><td>{d['coverage_value']}</td>"
            f"<td>{d['state_and_environment_control']}</td><td>{d['automation_readiness']}</td>"
            f"<td style='font-weight:700'>{d.get('requirement_weighted_score', '')}</td>"
            f"<td>{status}{warn_note}</td>"
            f"</tr>"
        )

    return f"""
    <h2>Manual Review Scores</h2>
    <p style="color:var(--muted);font-size:0.88rem;margin-bottom:8px">
      ⚠️ 人工评分，独立于自动化 checklist pass rate。8 维评分：Coverage Value 按 requirement case set 评分，其他维度按 case 评分。
    </p>

    <div class="summary-grid" style="margin-bottom:16px">
      <div class="summary-card">
        <div class="value" style="color:{score_color}">{avg}</div>
        <div class="label">Average Weighted Score (0-5)</div>
      </div>
      <div class="summary-card">
        <div class="value">{total_requirements}</div>
        <div class="label">Reviewed Requirements</div>
      </div>
      <div class="summary-card">
        <div class="value">{total_cases}</div>
        <div class="label">Reviewed Cases</div>
      </div>
      <div class="summary-card">
        <div class="value" style="color:{'var(--pass)' if unacceptable_count == 0 else 'var(--fail)'}">{unacceptable_count}</div>
        <div class="label">Unacceptable</div>
      </div>
    </div>

    <h3 style="margin-top:12px">Dimension Averages</h3>
    <table style="max-width:500px">
      <tr><th>Dimension</th><th>Avg</th><th>Min</th></tr>
      {"".join(dim_rows)}
    </table>

    <h3 style="margin-top:12px">Score Distribution</h3>
    {dist_bars}

    {unacceptable_html}

    <h3 style="margin-top:16px">Scored Cases (lowest first)</h3>
    <table>
      <tr><th>Req</th><th>Case</th><th>Align</th><th>Info</th><th>Exec</th><th>Obs</th><th>P/F</th><th>Cov</th><th>State</th><th>Auto</th><th>Req Weighted</th><th>Status</th></tr>
      {detail_rows if detail_rows else '<tr><td colspan="12" style="color:var(--muted)">No scored cases</td></tr>'}
    </table>"""


def main():
    run_dir = Path("optimization_runs/run_20260518_233620")
    prev_rate = None
    for rn in range(1, 6):
        rd = run_dir / f"round_0{rn}"
        if (rd / "generated_cases.json").exists():
            prev_rate = _generate_report(rd, rn, 5, prev_rate)


if __name__ == "__main__":
    main()
