import json
from datetime import datetime
from pathlib import Path

json_path = Path(__file__).parent / "gen_results.json"
results = json.loads(json_path.read_text(encoding="utf-8"))

rows: list[str] = []
for r in results:
    key = r["requirement_key"]
    func = r["function_name"]
    desc = r["description"].replace("\n", "<br>")
    signals = ", ".join(r["analysis_signals"]) or "—"
    thresholds = ", ".join(r["analysis_thresholds"]) or "—"
    timing = ", ".join(r["analysis_timing"]) or "—"
    plan_items = "".join(
        f'<li><b>{ci["coverage"]}</b> — {ci["description"]}</li>'
        for ci in r["analysis_plan"]
    )

    case_cards: list[str] = []
    for ci, c in enumerate(r["cases"]):
        q = "PASS" if c["quality_passed"] else "FAIL"
        q_color = "#16a34a" if c["quality_passed"] else "#dc2626"
        failures = "".join(f'<li style="color:#dc2626">{f}</li>' for f in c["quality_failures"])
        warnings = "".join(f'<li style="color:#d97706">{w}</li>' for w in c["quality_warnings"])
        steps_rows = "".join(
            f'<tr><td style="text-align:center;color:#888">{s["order"]}</td>'
            f'<td>{s["action"]}</td>'
            f'<td>{s["expected"]}</td></tr>'
            for s in c["steps"]
        )
        case_cards.append(f'''
        <div style="border:1px solid #ddd; border-radius:6px; padding:14px; margin-bottom:10px; page-break-inside:avoid">
          <h4 style="margin:0 0 6px 0">Case {ci+1} — {c["title"]}
            <span style="background:{q_color};color:#fff;padding:1px 8px;border-radius:3px;font-size:0.7rem;margin-left:8px">{q}</span>
          </h4>
          <p style="margin:4px 0"><b>Objective:</b> {c["objective"]}</p>
          <p style="margin:4px 0"><b>Precondition:</b> {c["precondition"]}</p>
          <table style="width:100%;border-collapse:collapse;margin:8px 0;font-size:0.85rem">
            <thead><tr style="background:#f5f5f5"><th style="width:40px;text-align:center">#</th><th style="width:45%">Action</th><th>Expected Result</th></tr></thead>
            <tbody>{steps_rows}</tbody>
          </table>
          <p style="margin:4px 0"><b>Postcondition:</b> {c["postcondition"]}</p>
          {f'<ul style="font-size:0.85rem;margin:4px 0">{failures}{warnings}</ul>' if failures or warnings else ''}
        </div>''')

    rows.append(f'''
    <div style="border:2px solid #2563eb; border-radius:8px; padding:18px; margin-bottom:24px; page-break-inside:avoid">
      <h2 style="margin:0 0 4px 0;color:#2563eb">{key}</h2>
      <p style="color:#888;margin:0 0 8px 0">{func}</p>
      <p style="background:#f8f9fa;padding:10px;border-radius:4px;font-size:0.95rem">{desc}</p>
      <div style="display:flex;gap:24px;font-size:0.85rem;margin:8px 0">
        <div><b>Signals:</b> {signals}</div>
        <div><b>Thresholds:</b> {thresholds}</div>
        <div><b>Timing:</b> {timing}</div>
      </div>
      <details style="margin:8px 0;font-size:0.85rem">
        <summary><b>Coverage Plan</b> ({len(r["analysis_plan"])} intents)</summary>
        <ul>{plan_items}</ul>
      </details>
      <h3 style="margin:12px 0 8px 0">{len(r["cases"])} Test Cases</h3>
      {''.join(case_cards)}
    </div>''')

html = f'''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>BMS Test Cases — Generated by qwen2.5:7b</title>
<style>
  body {{ font-family: system-ui, sans-serif; max-width: 1000px; margin: 0 auto; padding: 24px; color: #111; line-height: 1.5; background: #fafafa; }}
  h1 {{ color: #2563eb; }}
  footer {{ color: #888; font-size: 0.8rem; margin-top: 32px; text-align: center; }}
  @media print {{ body {{ background: #fff; }} }}
  table {{ border-collapse: collapse; width: 100%; }}
  th, td {{ border-bottom: 1px solid #ddd; padding: 6px 8px; vertical-align: top; }}
</style>
</head>
<body>
<h1>BMS HIL Test Cases</h1>
<p style="color:#888">Generated by <b>qwen2.5:7b</b> via Ollama — {datetime.now().strftime("%Y-%m-%d %H:%M")}</p>
{''.join(rows)}
<footer>Generated with Testcase Agent MVP — prompt-driven pipeline</footer>
</body>
</html>'''

out = Path(__file__).parent / "generated_cases.html"
out.write_text(html, encoding="utf-8")
print(f"Written: {out}")
